version: '3.4'

services:

  app:
    build: .
    command: >
      sh -c "python3 manage.py migrate &&
             python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis
      - db
  
  celery:
    build: .
    command: sh -c "python3 manage.py runworker"
    volumes:
        - .:/app
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    
    
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
volumes:
  postgres_data:

