# Generated by Django 5.2.9 on 2025-12-12 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='createdplaylist',
            name='original_author',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
